'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {calculate,currentWindow,hash,accountId,bindingFor}=require('../conversion/core.cjs');
const {parseLog,Collector}=require('../conversion/collector.cjs');const {Ledger}=require('../conversion/store.cjs');const {parsePricing,refreshPricing}=require('../conversion/pricing.cjs');const {ConversionService,hourlyTrend}=require('../conversion/service.cjs');
const start='2026-09-16T00:00:00.000Z',now='2026-09-16T01:00:00.000Z',end='2026-09-16T05:00:00.000Z',acct=accountId('synthetic');
function sample(){return {now,observation:{provider:'codex',status:'ok',sourceTimeKnown:true,sourceObservedAt:now,accountId:acct,windows:[]},window:{kind:'session',remainingPercent:80,resetsAt:end,windowMinutes:300},events:[{id:'a',eventKey:'a',revision:1,deviceId:'a',accountId:acct,occurredAt:'2026-09-16T00:30:00.000Z',model:'synthetic-model',serviceTier:'standard',input:800,cached:300,output:200}],coverage:[{deviceId:'a',from:start,to:now,complete:true,gaps:[]}],versions:[{id:'price-1',unit:'credits',fetchedAt:start,effectiveFrom:start,rates:[{model:'synthetic-model',tier:'standard',input:2,cached:0.2,output:10}]}],scope:{confirmed:true,accountId:acct,deviceIds:['a'],from:start}};}
test('one current snapshot and complete backfilled logs estimate without a zero snapshot or history',()=>{const r=calculate(sample());assert.deepEqual(r.reasons,[]);assert.equal(r.mode,'currentWindow');assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);assert.equal(r.devices[0].quota,20);assert.equal(r.range.start,start);assert.deepEqual(r.priceVersionIds,['price-1']);});
test('new Hub missing history is irrelevant; missing actual logs refuses and retains recorded tokens',()=>{const s=sample();s.coverage=[];const r=calculate(s);assert.equal(r.remainingTokens,null);assert(r.reasons.includes('coverageIncomplete'));assert.equal(r.devices[0].tokens,1000);});
test('seconds, minutes, timezone and start boundary are equivalent; end boundary and conflicting semantics fail',()=>{const s=sample();assert.equal(currentWindow(s.observation,{...s.window,windowMinutes:undefined,windowSeconds:18000,resetsAt:'2026-09-16T13:00:00+08:00'},now).start,start);for(const w of [{...s.window,windowSeconds:1},{...s.window,rolling:true},{...s.window,boundaryKind:'expiry'},{...s.window,windowMinutes:NaN}])assert(currentWindow(s.observation,w,now).reason);assert(!currentWindow({...s.observation,sourceObservedAt:start},s.window,start).reason);assert(currentWindow({...s.observation,sourceObservedAt:end},s.window,end).reason);});
test('late receive time never replaces official source time',()=>{const s=sample();s.observation.receivedAt=now;s.observation.sourceObservedAt=start;assert(calculate(s).reasons.includes('observationExpired'));s.observation.sourceTimeKnown=false;assert(calculate(s).reasons.includes('observationUnavailable'));});
test('unknown account retains recorded and priceable usage but prevents attribution',()=>{const s=sample();s.events[0].accountId=null;const r=calculate(s);assert.equal(r.devices[0].tokens,1000);assert(r.totalWeight>0);assert(r.reasons.includes('accountUnknown'));assert.equal(r.devices[0].quota,null);});
test('binding ranges do not silently extend; repeated same-account confirmation remains valid',()=>{const s=sample(),e={...s.events[0],accountId:null};const b={deviceId:'a',accountId:acct,from:start,to:now};assert.equal(bindingFor(e,[b,{...b,from:'2026-09-16T00:10:00.000Z'}]),acct);assert.equal(bindingFor({...e,occurredAt:end},[b]),null);assert.equal(bindingFor(e,[b,{...b,accountId:'other'}]),null);});
test('missing devices, unknown tier, price and cross-boundary daily buckets cannot become zeros',()=>{for(const mutate of [s=>s.scope.deviceIds.push('offline'),s=>s.events[0].serviceTier='unknown',s=>s.versions=[],s=>s.coverage=[{deviceId:'a',from:start,to:now,complete:false,basis:'daily'}]]){const s=sample();mutate(s);assert.equal(calculate(s).remainingTokens,null);}});
test('revisions supersede and duplicate event keys do not double count; allocation sums to observed use',()=>{const s=sample();s.events.push({...s.events[0],id:'retry'},{...s.events[0],id:'b',eventKey:'b',deviceId:'b'});s.scope.deviceIds.push('b');s.coverage.push({...s.coverage[0],deviceId:'b'});const r=calculate(s);assert.equal(r.devices.reduce((n,d)=>n+d.quota,0),20);assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);});
test('partial range fallback is labeled and ratio drops invalidate it',()=>{const s=sample(),prior='2026-09-16T00:20:00.000Z';s.coverage[0].from=prior;s.previous=[{...s.observation,sourceObservedAt:prior,windows:[{...s.window,remainingPercent:90}]}];assert.equal(calculate(s).mode,'coveredInterval');assert.equal(calculate(s).remainingTokens,null);assert.equal(calculate(s).attributionAvailable,true);s.previous[0].windows[0].remainingPercent=75;assert(calculate(s).reasons.includes('intervalIncomparable'));});
test('zero, cap, small percentages, invalid targets and zero weight never emit false balances',()=>{for(const remaining of [100,99,96,0,NaN,101]){const s=sample();s.window.remainingPercent=remaining;const r=calculate(s);assert.equal(r.remainingTokens,null);if(Number.isFinite(remaining)&&remaining<=100)assert.equal(r.devices[0].quota,100-remaining);else assert(r.devices.every(d=>d.quota===null));}const s=sample();s.events[0].input=0;s.events[0].cached=0;s.events[0].output=0;assert.equal(calculate(s).remainingTokens,null);});
test('historical price is not retroactively assumed; simulation remains separate',()=>{const s=sample();s.versions[0].effectiveFrom=null;s.versions[0].fetchedAt=now;const r=calculate(s);assert.equal(r.totalWeight,0);assert(r.simulationWeight>0);assert.equal(r.remainingTokens,null);});
function log(totals=[{input_tokens:800,cached_input_tokens:300,output_tokens:200}],fork=false){return [{timestamp:start,type:'session_meta',payload:{id:'synthetic-session',...(fork?{forked_from_id:'parent'}:{})}},{timestamp:start,type:'turn_context',payload:{model:'synthetic-model',service_tier:'default'}},...totals.map((total,i)=>({timestamp:new Date(Date.parse(start)+(i+1)*60000).toISOString(),type:'event_msg',payload:{type:'token_count',info:{total_token_usage:total,last_token_usage:total}}}))].map(JSON.stringify).join('\n');}
test('cumulative deltas dedup, exclude reasoning double count and never upload private text',()=>{const totals=[{input_tokens:100,cached_input_tokens:20,output_tokens:50,reasoning_output_tokens:40},{input_tokens:200,cached_input_tokens:40,output_tokens:100,reasoning_output_tokens:80}];const p=parseLog(log([totals[0],totals[0],totals[1]])+'\n'+JSON.stringify({type:'response_item',payload:{text:'PRIVATE'}}),'a');assert.equal(p.events.length,2);assert.equal(p.events.reduce((n,e)=>n+e.input+e.output,0),300);assert(!JSON.stringify(p).includes('PRIVATE'));assert.deepEqual(parseLog(log(totals),'a').events[0],parseLog(log(totals),'a').events[0]);});
test('fork inheritance and counter regression are gaps, not guessed cumulative consumption',()=>{assert.equal(parseLog(log(undefined,true),'a').events.length,0);assert(parseLog(log(undefined,true),'a').errors>0);const p=parseLog(log([{input_tokens:100,cached_input_tokens:20,output_tokens:50},{input_tokens:20,cached_input_tokens:2,output_tokens:5}]),'a');assert.equal(p.events.length,1);assert(p.errors>0);});
function temporary(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'conversion-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('SQLite queue and pagination checkpoint commit atomically and survive restart',t=>{const d=temporary(t);let l=new Ledger(d);l.put('events',{id:'a'},true);assert.throws(()=>l.transaction(()=>{l.set('cursor',{through:now});throw Error('interrupted')}));assert.equal(l.get('cursor'),null);l.close();l=new Ledger(d);assert.equal(l.pending('events').length,1);l.page('events',[{id:'b'}],'cursor',{through:now});assert.equal(l.get('cursor').through,now);l.ack('events',[{id:'a'}]);assert.equal(l.pending('events').length,0);l.close();});
test('backread duplicate files is idempotent and missing files remain coverage gaps on later scans',async t=>{const d=temporary(t),logs=path.join(d,'logs');fs.mkdirSync(logs);const f=path.join(logs,'a.jsonl');fs.writeFileSync(f,log());fs.writeFileSync(path.join(logs,'copy.jsonl'),log());const l=new Ledger(path.join(d,'db'));t.after(()=>l.close());l.set('coverageAttestation',{from:start,confirmed:true});const c=new Collector({ledger:l,deviceId:'a',roots:[logs]});await c.scan();assert.equal(l.rows('events').length,1);fs.unlinkSync(f);fs.unlinkSync(path.join(logs,'copy.jsonl'));await c.scan();assert(l.get('scan').errors>0);await c.scan();assert(l.get('scan').errors>0);assert.equal(l.rows('coverage').at(-1).complete,false);});
const table='#### Token rates\ncredits per million input tokens\n<table>'+['GPT-6 Astra','GPT-5.6 Sol','GPT-5.6 Terra'].map(m=>`<tr><td>${m}</td><td>100 credits</td><td>10 credits</td><td>500 credits</td></tr>`).join('')+'</table>\nFast mode applies a 2.5x multiplier to Astra';
test('official HTML table and explicit fast multiplier parse, malformed update retains previous version',async t=>{assert.equal(parsePricing(table).rates.length,4);const l=new Ledger(temporary(t));t.after(()=>l.close());await refreshPricing(l,async()=>({ok:true,text:async()=>table}));const id=l.get('pricingStatus').currentId;await refreshPricing(l,async()=>({ok:true,text:async()=>'invalid'}));assert.equal(l.rows('prices').length,1);assert.equal(l.get('pricingStatus').currentId,id);assert(l.get('pricingStatus').error);});
test('pagination failure retains data without advancing checkpoint, retry is idempotent',async t=>{let count=0;const s=new ConversionService({directory:temporary(t),deviceId:'a',fixture:true,request:async()=>{count++;if(count===2)throw Error('offline');return{schemaVersion:1,snapshotThrough:now,records:[{id:'a'}],nextCursor:count===1?'next':null};}});t.after(()=>s.close());await assert.rejects(()=>s.syncKind('api/usage/events','events'));assert.equal(s.ledger.rows('events').length,1);assert.equal(s.ledger.get('cursor:api/usage/events').cursor,'next');await s.syncKind('api/usage/events','events');assert.equal(s.ledger.rows('events').length,1);assert(s.ledger.get('cursor:api/usage/events').through);});

test('a second collector cannot own the same queue concurrently',t=>{const d=temporary(t),l=new Ledger(d);assert.throws(()=>new Ledger(d),/collectorAlreadyRunning/);l.close();const next=new Ledger(d);next.close();});

test('default window prefers usable consumption over an empty short window with inconsistent bounds',async t=>{
 const s=new ConversionService({directory:temporary(t),deviceId:'a',fixture:true});t.after(()=>s.close());const stamp=new Date().toISOString();
 s.ledger.put('observations',{id:'snapshot',provider:'codex',status:'ok',accountId:acct,sourceTimeKnown:true,sourceObservedAt:stamp,windows:[{kind:'session',windowMinutes:300,remainingPercent:100,resetsAt:new Date(Date.now()+18001000).toISOString()},{kind:'weekly',windowMinutes:10080,remainingPercent:57,resetsAt:new Date(Date.now()+86400000).toISOString()}]});
 const r=s.status();assert.equal(r.result.range.durationSeconds,604800);assert.equal(r.result.range.remaining,57);assert(!r.result.reasons.includes('observationExpired'));
});

test('window choices retain model lane labels so weekly limits are distinguishable',async t=>{
 const s=new ConversionService({directory:temporary(t),deviceId:'a',fixture:true});t.after(()=>s.close());const stamp=new Date().toISOString(),reset=new Date(Date.now()+86400000).toISOString();
 s.ledger.put('observations',{id:'lanes',provider:'codex',status:'ok',accountId:acct,sourceTimeKnown:true,sourceObservedAt:stamp,windows:[
  {kind:'weekly',limitId:'codex',windowMinutes:10080,remainingPercent:60,resetsAt:reset},
  {kind:'weekly',limitId:'gpt-5.3-codex-spark',additional:true,windowMinutes:10080,remainingPercent:90,resetsAt:reset}
 ]});
 const choices=s.rebuildStatus().choices;assert.deepEqual(choices.map(c=>c.label),['codex','gpt-5.3-codex-spark']);assert.equal(choices[1].additional,true);
});

test('status caches hourly revisions and falls back to the latest successful result for the same window',async t=>{
 const s=new ConversionService({directory:temporary(t),deviceId:'a',fixture:true});t.after(()=>s.close());
 const observed=new Date(),startAt=new Date(observed.getTime()-3600000).toISOString(),endAt=new Date(observed.getTime()+14400000).toISOString(),observedAt=observed.toISOString();
 const account=accountId('cached-history');
 s.ledger.put('prices',{id:'cached-price',unit:'credits',fetchedAt:startAt,effectiveFrom:startAt,rates:[{model:'synthetic-model',tier:'standard',input:2,cached:.2,output:10}]});
 s.ledger.put('events',{id:'cached-event',eventKey:'cached-event',revision:1,deviceId:'a',provider:'codex',accountId:account,occurredAt:observedAt,model:'synthetic-model',serviceTier:'standard',input:80,cached:30,output:20});
 s.ledger.put('coverage',{id:'cached-coverage',deviceId:'a',from:startAt,to:observedAt,complete:true,gaps:[]});
 s.ledger.set('config',{scope:{confirmed:true,accountId:account,deviceIds:['a'],from:startAt}});
 const window={kind:'session',limitId:'main',remainingPercent:80,resetsAt:endAt,windowMinutes:300};
 s.ledger.put('observations',{id:'good',provider:'codex',status:'ok',sourceDeviceId:'a',accountId:account,planLabel:'',sourceObservedAt:observedAt,sourceTimeKnown:true,windows:[window]});
 let r=s.rebuildStatus();assert.equal(r.displayMode,'current');assert.equal(r.trend.hourly.points.reduce((n,p)=>n+(p.tokens||0),0),100);assert.equal(r.result.devices[0].quota,20);
 const later=new Date(observed.getTime()+1000).toISOString();
 s.ledger.put('observations',{id:'bad',provider:'codex',status:'unknown',sourceDeviceId:'a',accountId:account,planLabel:'',sourceObservedAt:later,sourceTimeKnown:true,windows:[window]});
 r=s.rebuildStatus();assert.equal(r.displayMode,'historical');assert.equal(r.lastSuccessful.choiceId,r.choiceId);assert.equal(r.lastSuccessful.result.devices[0].quota,20);assert.equal(s.status().displayMode,'historical');
});

test('rolling hourly trend uses 24 absolute clock-aligned buckets and latest revisions',()=>{
 const observed=new Date('2026-09-16T17:42:00.000Z'),currentStart=new Date(observed.getFullYear(),observed.getMonth(),observed.getDate(),observed.getHours()),first=new Date(currentStart.getTime()-23*3600000);
 const event=(id,at,input,revision=1)=>({id,eventKey:id,revision,deviceId:'a',occurredAt:at.toISOString(),input,cached:0,output:0});
 const r=hourlyTrend([event('first',first,10),event('revised',new Date(first.getTime()+3600000),100),event('revised',new Date(first.getTime()+3600000),25,2),event('old',new Date(first.getTime()-1),999),event('future',new Date(observed.getTime()+120000),999)],observed);
 assert.equal(r.version,2);assert.equal(r.mode,'rolling24');assert.equal(r.points.length,24);assert.equal(Date.parse(r.rangeEnd)-Date.parse(r.rangeStart),24*3600000);assert.equal(Date.parse(r.points.at(-1).start)-Date.parse(r.points[0].start),23*3600000);assert.equal(r.points.reduce((n,p)=>n+(p.tokens||0),0),35);assert.equal(r.points[0].tokens,10);assert.equal(r.points[1].tokens,25);
});
test('rolling hourly trend keeps 24 absolute buckets across daylight-saving gaps and repeats',()=>{
 const previous=process.env.TZ;process.env.TZ='America/New_York';try{
  const spring=hourlyTrend([],new Date('2026-03-08T08:30:00.000Z')),fall=hourlyTrend([],new Date('2026-11-01T08:30:00.000Z'));
  for(const trend of [spring,fall]){assert.equal(trend.points.length,24);for(let i=1;i<24;i++)assert.equal(Date.parse(trend.points[i].start)-Date.parse(trend.points[i-1].start),3600000);}
  assert(!spring.points.map(p=>new Date(p.start).getHours()).includes(2));
  assert.equal(fall.points.map(p=>new Date(p.start).getHours()).filter(hour=>hour===1).length,2);
 }finally{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous;}
});

test('approximation uses current prices, Standard for unspecified tiers, all registered devices and keeps strict result separate',()=>{
 const {approximate}=require('../conversion/approximation.cjs'),s=sample();s.coverage=[];s.scope=null;s.events[0].accountId=null;s.events[0].serviceTier='unknown';s.versions[0].effectiveFrom=null;s.versions[0].fetchedAt=now;
 const strict=calculate(s),r=approximate({...s,deviceIds:['a','b','c','d']});assert.equal(strict.remainingTokens,null);assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);assert.equal(r.assumedTierTokens,1000);assert.equal(r.assumedAccountTokens,1000);assert.deepEqual(r.missingDevices,['b','c','d']);assert.equal(s.events[0].serviceTier,'unknown');assert.equal(r.devices[0].quota,20);
});
test('approximation excludes explicit other accounts and unpriced models; respects revisions, target weights and invalid reports',()=>{
 const {approximate}=require('../conversion/approximation.cjs'),s=sample();s.deviceIds=['a'];s.events.push({...s.events[0],id:'other',eventKey:'other',accountId:'other'},{...s.events[0],id:'unpriced',eventKey:'unpriced',model:'unknown'});
 let r=approximate(s);assert.equal(r.tokens,1000);assert.equal(r.excludedTokens,1000);assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);
 r=approximate({...s,target:{model:'synthetic-model',serviceTier:'standard',mix:[0,0,1]}});assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);
 for(const remaining of [100,99,0])assert.equal(approximate({...s,window:{...s.window,remainingPercent:remaining}}).remainingTokens,null);
 assert.equal(approximate({...s,window:{...s.window,rolling:true}}).remainingTokens,null);
});

test('legacy devices use explicit whole-day rate projections, without splitting boundary buckets or uploading invented events',()=>{
 const {approximate}=require('../conversion/approximation.cjs'),{aggregateDevice}=require('../conversion/summary-estimate.cjs');const s=sample();s.deviceIds=['a','b'];
 const d=aggregateDevice({deviceId:'b',updatedAt:now,accountEmail:'PRIVATE',periodWindows:{timeZone:'UTC'},history:{daily:[{date:'2026-09-15',perClient:{codex:{tokens:24000}},perModel:{'synthetic-model':{tokens:24000,cacheReadTokens:7200,outputTokens:4800}}},{date:'2026-09-16',perClient:{codex:{tokens:99999999}},perModel:{'synthetic-model':{tokens:99999999,cacheReadTokens:0,outputTokens:0}}}]}});
 assert(!JSON.stringify(d).includes('PRIVATE'));const r=approximate({...s,aggregateDevices:[d]});assert.equal(r.remainingTokens,null);assert.equal(r.attributionAvailable,true);assert.deepEqual(r.missingDevices,[]);assert.equal(r.devices.find(x=>x.id==='b').basis,'dailyRateProjection');assert.equal(r.devices.find(x=>x.id==='b').tokens,1000);assert.equal(s.events.length,1);assert(Math.abs(r.devices.reduce((n,d)=>n+d.quota,0)-20)<1e-10);
});

test('legacy target inputs never change attribution and prediction stays null',()=>{const s=sample(),a=calculate(s),b=calculate({...s,target:{model:'unknown',mix:[-1,2,3]}});assert.equal(a.remainingTokens,null);assert.equal(b.remainingTokens,null);assert.equal(a.models[0].quota,20);assert.deepEqual(a,b);});
